//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlmacenEntities : DbContext
    {
        public AlmacenEntities()
            : base("name=AlmacenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LugarEntrega> LugarEntregas { get; set; }
        public virtual DbSet<Proceso> Procesoes { get; set; }
        public virtual DbSet<Bodega> Bodegas { get; set; }
        public virtual DbSet<BodegaPantalon> BodegaPantalons { get; set; }
        public virtual DbSet<Bordado> Bordadoes { get; set; }
        public virtual DbSet<Cometario> Cometarios { get; set; }
        public virtual DbSet<Corte> Cortes { get; set; }
        public virtual DbSet<Detalle> Detalles { get; set; }
        public virtual DbSet<DetalleVenta> DetalleVentas { get; set; }
        public virtual DbSet<Diseño> Diseño { get; set; }
        public virtual DbSet<Lavanderia> Lavanderias { get; set; }
        public virtual DbSet<Maquila> Maquilas { get; set; }
        public virtual DbSet<Pantalon> Pantalons { get; set; }
        public virtual DbSet<Permiso> Permisoes { get; set; }
        public virtual DbSet<Prenda> Prendas { get; set; }
        public virtual DbSet<Talla> Tallas { get; set; }
        public virtual DbSet<TermiandoBodega> TermiandoBodegas { get; set; }
        public virtual DbSet<Terminado> Terminadoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Vendedor> Vendedors { get; set; }
        public virtual DbSet<Venta> Ventas { get; set; }
    }
}
