//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bodega
    {
        public Bodega()
        {
            this.BodegaPantalons = new HashSet<BodegaPantalon>();
            this.TermiandoBodegas = new HashSet<TermiandoBodega>();
        }
    
        public short Id { get; set; }
        public string Nombre { get; set; }
        public short IdUsuario { get; set; }
        public bool Estado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<BodegaPantalon> BodegaPantalons { get; set; }
        public virtual ICollection<TermiandoBodega> TermiandoBodegas { get; set; }
    }
}
