//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bordado
    {
        public short Id { get; set; }
        public string IdBordado { get; set; }
        public int NumeroPiezas { get; set; }
        public int NumeroPuntadas { get; set; }
        public string ParteBordada { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaTerminado { get; set; }
        public short IdPrenda { get; set; }
        public short IdUsuario { get; set; }
        public bool Estado { get; set; }
    
        public virtual Prenda Prenda { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
