//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diseño
    {
        public Diseño()
        {
            this.Pantalons = new HashSet<Pantalon>();
        }
    
        public short Id { get; set; }
        public string Codigo { get; set; }
        public string Corte { get; set; }
        public string Modelo { get; set; }
        public System.DateTime FechaAprovado { get; set; }
        public byte[] Imagen { get; set; }
        public short IdUsuario { get; set; }
        public bool Activo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Pantalon> Pantalons { get; set; }
    }
}
