//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pantalon
    {
        public Pantalon()
        {
            this.BodegaPantalons = new HashSet<BodegaPantalon>();
        }
    
        public short Id { get; set; }
        public int IdTalla { get; set; }
        public short IdDiseño { get; set; }
        public int Cantidad { get; set; }
    
        public virtual ICollection<BodegaPantalon> BodegaPantalons { get; set; }
        public virtual Diseño Diseño { get; set; }
        public virtual Talla Talla { get; set; }
    }
}
