//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public Permiso()
        {
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public short Id { get; set; }
        public bool Admin { get; set; }
        public bool Corte { get; set; }
        public bool Bordado { get; set; }
        public bool Maquila { get; set; }
        public bool Lavanderia { get; set; }
        public bool Terminado { get; set; }
        public bool Almacen { get; set; }
        public bool Venta { get; set; }
    
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
