//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermiandoBodega
    {
        public short IdTerminado { get; set; }
        public short IdBodega { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime IdUsuario { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        public virtual Terminado Terminado { get; set; }
    }
}
