//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Bodegas = new HashSet<Bodega>();
            this.Bordadoes = new HashSet<Bordado>();
            this.Cortes = new HashSet<Corte>();
            this.Diseño = new HashSet<Diseño>();
            this.Lavanderias = new HashSet<Lavanderia>();
            this.Maquilas = new HashSet<Maquila>();
            this.Terminadoes = new HashSet<Terminado>();
            this.Ventas = new HashSet<Venta>();
        }
    
        public short Id { get; set; }
        public string Nombre { get; set; }
        public string Usuario1 { get; set; }
        public string contrasena { get; set; }
        public short IdPermisos { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<Bodega> Bodegas { get; set; }
        public virtual ICollection<Bordado> Bordadoes { get; set; }
        public virtual ICollection<Corte> Cortes { get; set; }
        public virtual ICollection<Diseño> Diseño { get; set; }
        public virtual ICollection<Lavanderia> Lavanderias { get; set; }
        public virtual ICollection<Maquila> Maquilas { get; set; }
        public virtual Permiso Permiso { get; set; }
        public virtual ICollection<Terminado> Terminadoes { get; set; }
        public virtual ICollection<Venta> Ventas { get; set; }
    }
}
